{{- $name := "" }}
{{- with .instance.metadata.name }} {{ $name = . }} {{ end }}
{{- $namespace := "" }}
{{- with .instance.metadata.namespace }} {{ $namespace = . }} {{ end }}
{{- $ingress := "" }}
{{- with .plan.spec.context.clusterdomain }} {{ $ingress = . }} {{ end }}
{{- $fluentD := dict }}
{{- with .plan.spec.context.fluentd }} {{ $fluentD = . }} {{ end }}
{{- $kibana := dict }}
{{- with .plan.spec.context.kibana }} {{ $kibana = . }} {{ end }}
{{- $elasticsearch := dict }}
{{- with .plan.spec.context.elasticsearch }} {{ $elasticsearch = . }} {{ end }}
{{- $functiongetspace := "" }}
{{- with .plan.spec.context.functiongetspace }} {{ $functiongetspace = . }} {{ end }}
{{ $esingressEnabled := "false" }}
{{- with $elasticsearch.ingressEnabled }} {{ $esingressEnabled = . }} {{ end }}
{{- with  .instance.spec.parameters.esaccess }}
  {{- if . }}
    {{- $esingressEnabled = . }}
  {{- end }}
{{- end }}
{{- $fluentdUserKey := printf "fluentdUsername_%s" .binding.metadata.name }}
{{- $fluentdUserEnc :=  index .secret.data $fluentdUserKey}}
{{- $fluentdUser := "" }}
{{- with $fluentdUserEnc }}
  {{- $fluentdUser = b64dec $fluentdUserEnc }}
{{- end }}
{{- $fluentdPasswordKey := printf "fluentdPassword_%s" .binding.metadata.name }}
{{- $fluentdPasswordEnc :=  index .secret.data $fluentdPasswordKey}}
{{- $fluentdPassword := "" }}
{{- with $fluentdPasswordEnc }}
  {{- $fluentdPassword = b64dec $fluentdPasswordEnc }}
{{- end }}

{{- $host := "" }}
{{- with .service.spec.clusterIP }} {{ $host = . }} {{ end }}
{{- $pass := "" }}
{{- with .secret.data.POSTGRES_PASSWORD }} {{ $pass = (b64dec .) }} {{ end }}
{{- $xsuaaCreds := "" }}
{{- with .xsuaaBinding.status }}
  {{- if eq .state "succeeded"}}
    {{ $xsuaaCreds = .response }}
  {{- end }}
{{ end }}
{{- $stateString := "in progress" }}
{{- if and (and (not (eq $host "")) (not (eq $pass ""))) (not (eq $xsuaaCreds "")) }}
  {{- $stateString = "succeeded" }}
{{- end }}
{{- $responseString := "" }}
{{- if eq $stateString "succeeded"}}
  {{- $xsuaaCredsMap := unmarshalJSON $xsuaaCreds }}
  {{- $responseMap := dict "credentials" (dict "host" $host "username" "postgres" "password" $pass) "xsuaa" $xsuaaCredsMap }}
  {{- $responseString = mustToJson $responseMap }}
{{- end }}
xsuaaCreds: {{ $xsuaaCreds }}
stateString: {{ $stateString }}
responseString: {{ $responseString }}
apiVersion: abc.com/v1alpha1
kind: ABCD
metadata:
  name: abcd-{{ $name }}
  namespace: {{ $namespace }}
spec:
  elasticsearch:
    ingressEnabled: {{ $esingressEnabled }}
    data:
      cpu: {{ $elasticsearch.data.cpu }}
      disk: {{ $elasticsearch.data.disk }}
      memory: {{ $elasticsearch.data.memory }}
    master:
      cpu: {{ $elasticsearch.master.cpu }}
      disk: {{ $elasticsearch.master.disk }}
      memory: {{ $elasticsearch.master.memory }}
  fluentd:
    cpu: {{ $fluentD.cpu }}
    memory: {{ $fluentD.memory }}
    user: {{ $fluentdUser }}
    password: {{ $fluentdPassword }}
  kibana:
    cpu: {{ $kibana.cpu }}
    memory: {{ $kibana.memory }}
