instance:
  metadata:
    name: hello
    namespace: default
  spec:
    parameters:
      esaccess: false
binding:
  metadata:
    name: 24731fb8-7b84-5f57-914f-d3d55d793dd4
    namespace: default
  spec:
    parameters:
      esaccess: false

plan:
  spec:
    bindable: true
    context:
      clusterdomain: .abd.efg.hij.io
      elasticsearch:
        ingrsessEnabled: true
        data:
          cpu: 500m
          disk: 1Gi
          memory: 2048Mi
        master:
          cpu: 500m
          disk: 1Gi
          memory: 1024Mi
      fluentd:
        cpu: 200m
        memory: 512Mi
      kibana:
        cpu: 500m
        memory: 1024Mi
      functiongetspace: '{{ getSpace .Spec.Es.Data.MaxNodeCount .Spec.Es.Data.VolumeStorage
        .Spec.Es.Data.Percentage }}'
    description: hello world
    free: true
    id: 872131dc-7011-11e9-a923-1681be663d3e
    manager:
      async: true
      settings:
        dashboard_url_template: aHR0cHM6Ly9hYmMtc2YtaW5zdGFuY2VpZC5hYmMuZGVmLmhpai5pbwo=
    metadata:
      bullets:
      - Container Deployment
      - 512MB Elastic search node
      - 1GB Disk
      costs:
      - amount:
          usd: 0
        unit: MONTHLY
      service-inventory-key: SERVICE-TBD
    name: standard
    serviceId: 74726c04-7011-11e9-a923-1681be663d3e

secret:
  data:
    POSTGRES_PASSWORD: cGFzc3dvcmQK
    fluentdPassword_24731fb8-7b84-5f57-914f-d3d55d793dd4: cGFzc3dvcmQK

service:
  spec:
    clusterIP: 192.168.55.65

xsuaaBinding:
  status:
    state: succeeded
    response: '{"uaa":{"apiurl":"sss","clientid":"ssss","clientsecret":"sss=","identityzone":"service-fabrik","identityzoneid":"service-fabrik","sburl":"sss","tenantid":"service-fabrik","tenantmode":"dedicated","uaadomain":"authentication.com","url":"https://service.com","verificationkey":"-----BEGIN PUBLIC KEY-----MI-----END PUBLIC KEY-----","xsappname":"products"}}'
